services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpw
      POSTGRES_DB: appdb
    # Mount the seed SQL so it runs on FIRST init
    volumes:
      - "C:/Users/saiha/Desktop/Cloud_Assignment2/Cloud_assignment2/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 3s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: appuser
      DB_PASS: secretpw
      DB_NAME: appdb
      APP_TOP_N: "10"
    # ABSOLUTE host path → /out in container
    volumes:
      - "C:/Users/saiha/Desktop/Cloud_Assignment2/Cloud_assignment2/out:/out"
